name: Astronomer CI - Deploy code

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Astro CLI
      run: curl -sSL https://install.astronomer.io | sudo bash -s

    - name: Deploy DAGs
      run: astro deploy ${{ secrets.ASTRO_DEPLOYMENT_ID }} --dags --force --workspace-id ${{ secrets.ASTRO_WORKSPACE_ID }}
      env:
        ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
